---
title: 'midori1'
author: "Toshihide Imaruoka"
output:
  rmdformats::downcute:
    highlight: kate
    css: mycss.css
    dev: "ragg_png"
---
# エピグラフ
  - 赤池弘次先生：モデルの良さの指標で知られるAICで有名。
  
# まえがき
  - 「数理モデルで現象を表現・説明する」
  - 一般化線形モデル（GLM: generalized linear model）
    - 前半でGLM入門
    - 後半でベイズ統計モデル
  - ソフトウェアとサポートWebサイト
    - R
    - WinBUGS: マルコフ連鎖モンテカルロ（MCMC）法を行うためのソフトウェア
      - MCMC法はR上で動くStanやBRMSというソフトでも計算できる
      - 使う頃になったら、そのあたりは勉強会でも扱いましょう
    - [サポートWeb](https://kuboweb.github.io/-kubo/ce/IwanamiBook.html)
    
# 1章
## 1.1 統計モデル：なぜ「統計」な「モデル」？
  - 統計モデル（statistical model）とは
    - データとして観測された現象を説明するため
    - データにあるばらつきを説明するために確率分布を利用
    - 観測データとモデルの当てはまり具合を評価可能
  - P3の図
    - 情報の（消失と言ってるけど、実際には）要約
    - 自然界で観測できる現象の本質を知るために、なるべくうまく要約したい
    - そのためには確率分布という部品は不可欠
    
## 1.2 「ブラックボックスな統計解析」の悪夢
  - 悪夢たち＝QRPs(Questionable Research Practices)
    - 検定手法の繰り返し：計画していた相関係数の検定では効果が見られなかったから群分けしてt検定してみよう、とか
    - 謎指標の作成：統制条件との差では効果がなかったから比を取る、とか
    - $R^2$の解釈：重回帰式の$R^2$が小さいから説明変数を増やしてみよう、とか
    - データの変数変換：反応時間データは角変換するもの、と習ったような...
    - ノンパラ：これは具体的な例が浮かばなかった
    - 多重比較：これもそうするもんだって習ったような...
    - P値：P値と有意水準の比較が全てとは分かっていてもP値が小さいと喜んでしまう...
    
## 1.3 この本の内容：一般化線形モデルの導入とそのベイズ的な拡張
  - 一般化線形モデルと「これまでの」統計手法（＝線形モデル）の違い
    - 線形モデル：「自然界で観測されるデータは正規分布する」
    - 一般化線形モデル：現象によって分布の種類は異なる
      - 2章ではまずはカウントデータから（＝カウントデータは正規分布しない）

## 1.3.1 各章の内容--全体の説明の流れ
  - 2章
    - 確率分布の説明：例としてポアソン分布（＝カウントデータに使う）
    - パラメータを推定する：最尤推定
  - 3章
    - 一般化線形モデル
      - ポアソン回帰：ポアソン分布・リンク関数・線形予測子を使ってデータを表現
  - 4, 5章
    - モデルの比較：AIC
  - 5章
    - 最大対数尤度
    - 尤度比検定
  - 6章
    - 色々な確率分布を使ったGLM
      - 二項分布・ロジスティック回帰：2値データ
      - 正規分布：あまり制約のない連続量データ
      - ガンマ分布：正の数のみとる連続量データ
  - 7章
    - 一般化線形混合モデル（GLMM: generalized linear mixed model）
      - 統計モデルにランダム効果（＝個人差など）を
  - 8章
    - MCMC
    - ベイズ統計モデル
  - 9章
    - GLMのベイズモデル化
    - ソフトウェアを使った推定（WinBUGS）
  - 10章
    - 階層ベイズモデル
  - 11章
    - 階層ベイズモデルの応用：空間構造を考慮した統計モデル

## 1.4 この本に登場する訳語・記号・記法について
  - 定まった訳語がないもの
    - 逸脱度：deviance
    - 残差逸脱度：residual deviance
    - 固定効果：fixed effects
    - ランダム効果: random effects
    - リンク関数：link function
  - 最近用語が変わりつつあるもの
    - 応答変数：response variable
      - 従属変数：dependent variable
      - 目的変数という言い方も
    - 説明変数：explanatory variable
      - 独立変数：independent variable
  - 式
    - 応答変数$y_i$, 説明変数$\{x_i, f_i\}$
      - $f(y_i)=\beta_1+\beta_2x_i+\beta_3f_i+...$
    - $f(y_i)$: 応答変数のリンク関数
    - 右辺：線形予測子
    - $\beta_1$（説明変数を伴わない）：切片
    - $\beta_2$（説明変数などを伴う）：傾き
  - この本の書き方
    - 積の記号（$\times$）、カッコ（log$(x)$をlog$x$）を省略（本ではlogと書いてるけど、伊丸岡の資料では$log$と斜体にします。打ち込むのが面倒という理由）
    - 指数関数：exp$x=e^x$、$e$は自然対数の底（である定数）
    - 対数関数：log$x$はlog$_ex$
    - $i\in\{1,2, ..., 50\}$：$i$は個体番号1から50まで
    - 個体を$y_i$と表すとき、個体を特定せずに指すために$y$と表記する場合がある
    - $y*$：$y$のどれでもいい
    - 和記号（$\sum$）の下に$i$（$\sum_i$）：全ての個体の和
    - 積記号（$\prod$）の下に$i$：全ての個体の積
    - 丸めた場合も$\approx$ではなく等号$=$を使う
    - $\propto$は比例
    - $確率変数\sim 確率分布$：確率変数は確率分布に従う
    - $p(A,B)$：同時確率（AとBがどちらも生起する確率）
    - $p(A|B)$：条件付き確率（Bが起きたという条件のもとでAが起きる確率）
    - 集合、ベクトル、行列を太字表記するというルールもあるが、この本では従わない。ただし　例外もあり。
    
## おまけ
  - 資料作りについて
    - この本の特徴
      - 数式を表現する機会が多い
      - 図を表現する機会も多い
      - Rのコードが出てくることも結構ある
    - これらが簡単にできる方法で資料を作ると楽
    - いくつかの選択肢
      - 伊丸岡の場合
        - RstudioでR Markdown形式で作っている
          - [TeX記法](https://medemanabu.net/latex/operators/)で数式を書ける
          - チャンクという機能でRのコードを書き、それを実行して出力もできる(下に例)
        - それをhtmlで書き出している
        - ついでにGitHubで公開している
          - [R Markdown + Githubでモダンな個人Webサイト構築](https://kazutan.github.io/HijiyamaR6/rmd_de_github_site.html#/)
          - [imaru public memo](https://imaru.github.io/pubmemo/)
          
```{r}
m<-0
v<-1
xdat<-seq(-3,3,0.01)
ydat<-(1/sqrt(2*pi*v))*exp(-(xdat-m)^2/(2*v))
plot(xdat, ydat, type='l')
```
          
