---
title: "心理科学科技術部"
author: "Toshihide Imaruoka"
date: "6/18/2021"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 技術部とは

- 心理学で使える技術を身につけることを目的とした学生プロジェクト

## 何のため?

- AIとか機械学習とか色々な生体センサーとか新しい技術がたくさん
  - 開発は無理だけど使うことのハードルは高くない
- 使うと本当に色々なことができる
  - んだけど、PD3で使う人は多くない
  - し、半年一生懸命頑張った資産が残らない
- 使いたい・残したい・使っておもしろいことをやる人を増やしたい

## 技術？

- ソフトウェア
- ハードウェア
- Web・ネットワーク

## 心理学で使えるソフトウェア技術

- [Psychtoolbox @ MATLAB / Octave](http://psychtoolbox.org/)
- [PsychPy](https://www.psychopy.org/)
- [顔認識 @ MATLAB機械学習](https://jp.mathworks.com/help/vision/ug/detect-and-track-face.html)
- [音声認識 @ MATLAB機械学習](https://jp.mathworks.com/help/deeplearning/ug/deep-learning-speech-recognition.html)
- [2次元映像からの人体検出 OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose)
- [2次元映像からの顔・表情検出 OpenFace](https://github.com/TadasBaltrusaitis/OpenFace)
- [VR構築 Unity](https://unity.com/ja)

## 心理学で使えるハードウェア技術

- [視線計測](https://pupil-labs.com/)
- [脳計測](http://www.east-medic.jp/category/eeg/)
- VRゴーグル
  - [HTC Vive](https://www.vive.com/jp/)
  - [Oculus Quest](https://www.oculus.com/compare/)
- [深度カメラ Azure Kinect](https://azure.microsoft.com/ja-jp/services/kinect-dk/)

## Web・ネットワーク

- [ネットワーク用心理実験ライブラリ JsPsych](https://www.jspsych.org/)
- [レンタルサーバ imrlab.org](https://tradtech.imrlab.org/eval/bone117.htm)
- [バージョン・ソース管理 github](https://github.com/)

## 技術を支える基盤

- プログラミング・スクリプト言語
  - python
  - Matlab
  - R
- PC上の環境
  - [Windows Subsystem for Linux](https://docs.microsoft.com/ja-jp/windows/wsl/install-win10)
  - [Homebrew](https://brew.sh/index_ja)

## 進め方（案）

- 1人あるいは少数のグループで一つのテーマに取り組む
  - グループも役割分担というよりは、それぞれが進めるイメージ
- 週に一度のミーティング
  - こんなことできるようになりました！の発表会
  - ここで困ってますの相談
- 基盤技術については皆で作業することがあってもいいかも
  - なくてもいいかも

## 不安な点

- 明確なゴールがない
- 必ずしも指導できない

## プロジェクトにする意味

- ソロ活動はモチベーションが保ちにくい
  - 自慢したい
- 技術の継承
  - （毎年教えるのがしんどい）
- 相乗効果というものは確実にある